[project]
name = "helix"
version = "1.0.0"
description = "Nuxt 3 Template for Static Website"
readme = "README.md"
requires-python = "==3.13.*"
authors = [{ name = "Meryll Dindin", email = "merylldin@gmail.com" }]
dependencies = []

[dependency-groups]
devops = ["sirtuin==1.2.0"]
